### ISSUE TITLE
api_breed.lua:189: attempt to index local 'obj' (a nil value)

### ISSUE THREAD

**Issue by Bastrabun** [runsy/petz#166] opened 2023-04-28 12:58 UTC
```
2023-04-28 11:32:57: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'petz' in callback luaentity_Step(): ....1/Minetest_live/bin/../mods/petz/petz/api/api_breed.lua:189: attempt to index local 'obj' (a nil value)
2023-04-28 11:32:57: ERROR[Main]: stack traceback:
2023-04-28 11:32:57: ERROR[Main]: ....1/Minetest_live/bin/../mods/petz/petz/api/api_breed.lua:189: in function 'growth_timer'
2023-04-28 11:32:57: ERROR[Main]: .../Minetest_live/bin/../mods/petz/petz/api/api_on_step.lua:10: in function 'on_step'
2023-04-28 11:32:57: ERROR[Main]: ...etest_live/bin/../mods/petz/petz/petz/chicken_mobkit.lua:151: in function 'func'
2023-04-28 11:32:57: ERROR[Main]: ...inetest_live/bin/../builtin/profiler/instrumentation.lua:107: in function 'old_on_step'
2023-04-28 11:32:57: ERROR[Main]: ...ve/bin/../mods/yl_commons/bugfixes/petz_spawn_height.lua:27: in function <...ve/bin/../mods/yl_commons/bugfixes/petz_spawn_height.lua:20>
```

For my reference 4324

**Comment by runsy** [comment] 2023-04-28 14:26
What is petz_spawn_height.lua?

**Comment by g-whiz** [comment] 2023-04-29 17:34
> What is petz_spawn_height.lua?

That seems to be downstream code specific to the YourLand server. Probably this should be closed and marked as wontfix.

**Comment by fluxionary** [comment] 2023-05-02 19:29
> > What is petz_spawn_height.lua?
> 
> That seems to be downstream code specific to the YourLand server. Probably this should be closed and marked as wontfix.

it's not relevant. the issue is that `minetest.add_entity` returned nil (the entity wasn't created), and there is no check for that.

**Closed** 2023-05-02 21:02 UTC
